### ISSUE TITLE
TinyTex doesn't render Unicode \U2264 correctly

### ISSUE THREAD

**Issue by lhunsicker** [yihui/tinytex#227]
I have written a .Rmd file (attached) which includes a unicode character (\u2264, <=) in some figure headings. When I render the code within the RStudio source window .Rmd document or as a Word document, it renders correctly. But when I compile the document to latex using tinytex/TinyTex (using either pdflatex or xelatex to convert the latex to pdf) the character is rendered incorrectly as "=".  It seems probable that the problem is at the tinytex/TinyTex stage, and probably results from the default font files lacking the \u2264 character. 
The below is a reproducible (on my machine) example,.
```
---
title: "TestCase"
author: "Hunsicker LG"
date: "7/13/2020"
output:
  pdf_document
---

## R Markdown

This is an R Markdown test document.

```{r setup, echo = F, eval = TRUE, include = T}
library(knitr)
library(survminer)
library(survival)
df1 <- data.frame(time = rnorm(100, 100, 20),
                  event1 = sample(0:1, 100, replace = T),
                  covar1 = sample(0:1, 100, replace = T))
model1 = survfit(Surv(time, event1) ~ covar1, data = df1)
ggsurvplot(fit = model1, risk.table = F, xlab = 'Years', 
           pval = F, title = "Junk \u2264 Stuff")
```
```
Running R 4.0.2 on RStudio 1.3.959 and all packages up-to-date, on Windows 10, also up-to-date.  In addition, I also ran:
tinytex:::is_tinytex() (TRUE)
tinytex:::install_yihui_pkgs()
tinytex::tlmgr_update()
None of these solved the problem.


> xfun::session_info('tinytex') R version 4.0.2 (2020-06-22) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 18363), RStudio 1.3.959  Locale:   LC_COLLATE=English_United States.1252    LC_CTYPE=English_United States.1252      LC_MONETARY=English_United States.1252   LC_NUMERIC=C                             LC_TIME=English_United States.1252      Package version:   graphics_4.0.2  grDevices_4.0.2 stats_4.0.2     tinytex_0.24      tools_4.0.2     utils_4.0.2     xfun_0.15

I have three questions:

How do I determine what the default Latex font(s) are?
What Latex font(s) would have the \u2254 character (and more generally, other math characters)?
And finally, how would I install a font that DOES have the \u2254 character without messing up the rest of the formatting? Can I do this by including something in the .Rmd file header?

Thanks in advance for any help you can give me. |  

Larry Hunsicker
-- | --

<!--
Please keep the below portion in your issue. Your issue will be closed if any of the boxes is not checked. In certain (rare) cases, you may be exempted if you give a brief explanation (e.g., you are only making a suggestion for improvement). Thanks!
-->

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [ X] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.  (RStudio Community -- 48 hours)  URL:  https://community.rstudio.com/t/rendering-unicode-in-knitr-to-pdf/72844
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('tinytex')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/tinytex')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [X ] I have learned the Github Markdown syntax, and formatted my issue correctly.  (I think!)

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by lhunsicker** [comment]
Addendum:
I tried running this toy Rmd file in RStudio on my Ubuntu box,  The result was more informative than the result on my Windows 10 box.  Compile failed, but gave an error that made sense to me, together with a batch of warnings that all clearly refer to the problematic figure title "Less \u2264 More".  The full output is below, with the critical part bolded.    The problem is that \u2264 is not defined for inputenc.  I am now trying to learn enough Latex to figure out how to define that character, and then how to include it in the .Rmd header.  But if any of you can tell me how to do this, I would be very grateful.  LGH

> rmarkdown::render('CKDEpi.Rmd', clean = F)
> 
> 
> processing file: CKDEpi.Rmd
>   |.....................................                                     |  50%
>   ordinary text without R code
> 
>   |..........................................................................| 100%
> label: setup (with options) 
> List of 3
>  $ echo   : symbol F
>  $ eval   : logi TRUE
>  $ include: symbol T
> 
> 
> output file: CKDEpi.knit.md
> 
> /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS CKDEpi.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output CKDEpi.tex --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --lua-filter /home/larry/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /home/larry/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmd/lua/latex-div.lua --variable 'geometry:margin=1in' 
**> ! Package inputenc Error: Unicode char ≤ (U+2264)
> (inputenc)                not set up for use with LaTeX.**
> 
> Error: LaTeX failed to compile CKDEpi.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See CKDEpi.log for more info.
> In addition: There were 27 warnings (use warnings() to see them)
> > warnings()
> Warning messages:
> 1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 4: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 5: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 6: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 7: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 8: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 9: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 10: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 11: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 12: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 13: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 14: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 15: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 16: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 17: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 18: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 19: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 20: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 21: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 22: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 23: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 24: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
> 25: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <e2>
> 26: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <89>
> 27: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
>   conversion failure on 'Junk ≤ Stuff' in 'mbcsToSbcs': dot substituted for <a4>
>

**Comment by cderv** [comment]
For reference, this has also been posted on the Rstudio Community
https://community.rstudio.com/t/rendering-unicode-in-knitr-to-pdf

**Comment by lhunsicker** [comment]
cderv solved my problem (if not all of my questions) in the above reply at community.rstudio.com.  In sum, he suggested changing the default graphics device for pdf_output to either png or the new ragg_png.  Both render the above toy document perfectly -- both in Windows 10 and in Ubuntu 18-04.  As noted above, the Ubuntu version of the Ubuntu pdf device used as default by pdf_output evidently uses latex code, given the error output.  Since my problem is solved, I am not much interested in trying to fix-up the default pdf_device.  The solution is just not to use that device, and now I know how to change the device.
Many thanks to cderv!!  LGH

**Comment by MavropaliasG** [comment]
@cderv I can't reopen the issue in the forum, but I am trying to knit to PDF with both `dev: png` and `dev: ragg_png` and it doesn't work, I still get 

`! LaTeX Error: Unicode character ≤ (U+2264)
               not set up for use with LaTeX.`

This is in Rstudio 2022.07.1 Build 554 in Manjaro Linux, running RMarkdown 2.17 and knitr 1.4. The only latex installation in my system is through Rstudio, package tinytex 0.42.

Can you please let me know why is it not rendering?

**Comment by yihui** [comment]
When you see a LaTeX error about a certain Unicode character not set up, I think the most likely solution is to use the LaTeX engine `xelatex` instead of the default `pdflatex` to compile the document: https://bookdown.org/yihui/rmarkdown/pdf-document.html#latex-engine

**Comment by MavropaliasG** [comment]
@yihui thank you so much, adding

```
    latex_engine: xelatex
```

Fixed the problem. Thank you
