### ISSUE TITLE
install_tinytex() - Failed on Windows 10

### ISSUE THREAD

**Issue by stevenconnorg** [yihui/tinytex#45]
Hi Yihui,

I'm trying to share a bookdown project with a co-worker, so I'm attempting to install tinytex on their machine. I followed the same steps that I took, but whenever I run it on her machine I get this error:

> Starting to install TinyTeX to C:\Users\Marie\AppData\Roaming/TinyTeX. It will take a few minutes.
PATH=C:\Users\Marie\AppData\Local\Temp\RtmpiclSRu\install-tl-20180521\tlpkg\tlperl\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Dell\DW WLAN Card;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\GnuWin32\bin;C:\Users\Marie\AppData\Roaming\TinyTeX\bin\win32\tlmgr;C:\Users\Marie\AppData\Local\Microsoft\WindowsApps;C:\Users\Marie\AppData\Roaming\TinyTeX\bin\win32
"C:\Users\Marie\AppData\Local\Temp\RtmpiclSRu\install-tl-20180521\install-tl" -profile=../texlive.profile
Automated TeX Live installation using profile: ../texlive.profile
TeXLive::TLUtils::setup_programs (w32) failed at C:/Users/Marie/AppData/Local/Temp/RtmpiclSRu/install-tl-20180521/tlpkg/TeXLive/TLUtils.pm line 2347.
C:\Users\Marie\AppData\Local\Temp\RtmpiclSRu\install-tl-20180521\tlpkg\installer\lz4\lz4.exe --version failed (status 256): No such file or directory
Output is:
The system cannot find the path specified.

> C:\Users\Marie\AppData\Local\Temp\RtmpiclSRu\install-tl-20180521\install-tl: Goodbye.
TinyTeX installed to C:\Users\Marie\AppData\Roaming/TinyTeX
Restart your R session and check if tinytex:::is_tinytex() is TRUE.
Warning messages:
1: In file.remove("TinyTeX/install-tl.log") :
  cannot remove file 'TinyTeX/install-tl.log', reason 'No such file or directory'
2: running command '"bin/win32/tlmgr" install latex-bin xetex amscls amsfonts amsmath bibtex booktabs caption dvipdfmx ec etoolbox fancyvrb fontspec framed geometry graphics graphics-def gsftopk hyperref ifluatex ifxetex lm luaotfload makeindex mathspec metafont mfware natbib oberdiek titling tools upquote url xkeyval zapfding' had status 127 
3: running command '"bin/win32/tlmgr" path add' had status 127 
4: running command '"bin/win32/tlmgr" conf auxtrees add "C:/PROGRA~1/R/R-34~1.1/share/texmf"' had status 127 

I've also tried to [batch file](https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-windows.bat), but got the same error.

Any ideas?

Kindly,
Steven G.

**Comment by yihui** [comment]
This is due to an unfortunate bug in TeX Live, which is said to have been fixed but I have no idea when the fix will be available in their installer: https://tex.stackexchange.com/q/432617/9128

**Comment by stevenconnorg** [comment]
Thanks Yihui! I'll keep an eye on the TeX Live installer.

**Comment by stevenconnorg** [comment]
Thanks Yihui! I'll keep an eye on the TeX Live installer.

**Comment by yihui** [comment]
If you cannot wait, you can actually copy your TinyTeX folder to your co-worker's computer (if both of you are using Windows), and run the command `tlmgr path add` there. The only tricky thing is you will need the full path to `tlmgr`. See FAQ 11: https://yihui.name/tinytex/faq/

**Comment by stevenconnorg** [comment]
Thank you for the work-around. I ended up get an error stating:

> Use of uninitialized value in bitwise of (|) at C:\path\to\texmf-dist\scripts\texlive\tlmgr.pl line 1479.

I realized that my co-worker didn't have Perl installed, but after getting that installed, I still get the same error. I understand that this really isn't a TinyTeX issue, per se, but do you happen to have any ideas?
